### PR TITLE
Add runPromise function

### LINKED ISSUE #26: Make Time.run() return a promise
As already mentioned in #21 
Would simplify tests like [here](https://github.com/cyclejs-community/create-cycle-app-flavors/pull/16/files/d9c6d7c55914ab6e4e19beb1ff07fe13070943e9#diff-218bf2ca75d93d9f4b29817e167321c2R49) (https://github.com/cyclejs-community/create-cycle-app-flavors/pull/16)
Important would be that the Promise resolves to `true` in the passing case.

### PR DESCRIPTION
**Pull request by jvanbruegge**
Fixes #26 
This way it is not a breaking change

### CODE REVIEW

**Comment by jvanbruegge** [comment]
I tested it locally and it worked just fine

**Comment by Widdershin** [comment]
Thanks for making this PR. I want to support promises, but I'm averse to adding more to the API surface. I'm not as concerned about breaking changes, as we've yet to release `v1.0.0`.

I'll hold off on merging this, as I think what we'll probably do is just make `run()` return a promise and drop support for callbacks altogether.

**Comment by staltz** [comment]
An outsider opinion here: I think this is just a matter of preference, there isn't one option which is clearly better than the other.

```diff
-it('should test', (done) => {
+it('should test', () => {
   // ...

-  Time.run(done);
+  return Time.runPromise();
 });
```

Notice both cases have comparable amount of characters to type.

And since you can make a promise from a callback rather easily, in https://github.com/cyclejs-community/create-cycle-app-flavors/pull/16/files/d9c6d7c55914ab6e4e19beb1ff07fe13070943e9#diff-218bf2ca75d93d9f4b29817e167321c2R49 you could just make a helper function

```js
return helper(Time.run);
```

```js
function helper(run) {
  return new Promise((resolve, reject) => run(err => err ? reject(err) : resolve(true)));
}
```

**Comment by jvanbruegge** [comment]
Yes, this PR basicly integrates this helper in `@cycle/time`
It is nothing more than a wrapping function, so not everyone has to write this helper for himself

**Comment by staltz** [comment]
Maybe I didn't make it obvious, but my point was that this below is generic and could be used by anything, outside of `@cycle/time`

```js
function helper(run) {
  return new Promise((resolve, reject) => run(err => err ? reject(err) : resolve(true)));
}
```

In fact... https://www.npmjs.com/package/pify

**Comment by mightyiam** [comment]
@staltz eventually, promises and streams are also fancy callbacks. It is interoperable both ways, isn't it?

**Comment by jvanbruegge** [comment]
closing in favor of #32

**Pull request closed without merging**
